version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017" #port mapping
    networks:
      - dropw-mongodb-ntw
  ui-server:
    image: ui-server:latest
    container_name: nginx-server
    restart: always
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - dropw-mongodb-ntw

  dropwizard-server:
    image: dropwizard-server:latest
    container_name: dropwizard-ms
    command: ["java", "-jar", "ds-project1-1.0-SNAPSHOT.jar", "server", "config.yml"]
    ports:
      - "8090:8080"
      - "8091:8081"
    networks:
      - dropw-mongodb-ntw
    depends_on:
      - mongodb


networks:
  dropw-mongodb-ntw:
    name: dropw-mongodb-ntw

