version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017" #port mapping
    networks:
      - dropw-mongodb-ntw

  dropwizard-server:
    image: dropwizard-server:latest
    container_name: dropwizard-broker
    command: ["java", "-jar", "ds-project1-1.0-SNAPSHOT.jar", "server", "config.yml"]
    ports:
      - "8090:8080"
      - "8091:8081"
    networks:
      - dropw-mongodb-ntw
    depends_on:
      - mongodb

  dropwizard-publisher:
    image: dropwizard-publisher:latest
    container_name: dropwizard-publisher
    command: [ "java", "-jar", "publisher-1.0-SNAPSHOT.jar", "server", "config.yml" ]
    ports:
      - "8070:8070"
      - "8071:8071"
    networks:
      - dropw-mongodb-ntw
    depends_on:
      - dropwizard-server


networks:
  dropw-mongodb-ntw:
    name: dropw-mongodb-ntw

